// This file is generated by Firebase Extensions.
'use server';
/**
 * @fileOverview AI-powered tool that analyzes a portfolio and suggests improvements
 * based on trending design styles to attract more views and engagement.
 *
 * - portfolioOptimizer - A function that handles the portfolio optimization process.
 * - PortfolioOptimizerInput - The input type for the portfolioOptimizer function.
 * - PortfolioOptimizerOutput - The return type for the portfolioOptimizer function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const PortfolioOptimizerInputSchema = z.object({
  portfolioDescription: z
    .string()
    .describe('A detailed description of the current portfolio, including the type of work, target audience, and any specific design choices.'),
  designGoals: z
    .string()
    .describe('Specific goals for the portfolio, such as increasing views, attracting specific clients, or improving engagement.'),
});
export type PortfolioOptimizerInput = z.infer<typeof PortfolioOptimizerInputSchema>;

const PortfolioSuggestionSchema = z.object({
  suggestion: z.string().describe('A specific suggestion for improving the portfolio.'),
  confidence: z
    .number()
    .describe('A confidence score (0-1) indicating the likelihood that the suggestion will increase views or engagement.'),
  reasoning: z.string().describe('The reasoning behind the suggestion, including references to trending design styles.'),
});

const PortfolioOptimizerOutputSchema = z.object({
  suggestions: z.array(PortfolioSuggestionSchema).describe('An array of suggestions for improving the portfolio, ranked by confidence.'),
});

export type PortfolioOptimizerOutput = z.infer<typeof PortfolioOptimizerOutputSchema>;

export async function portfolioOptimizer(input: PortfolioOptimizerInput): Promise<PortfolioOptimizerOutput> {
  return portfolioOptimizerFlow(input);
}

const prompt = ai.definePrompt({
  name: 'portfolioOptimizerPrompt',
  input: {schema: PortfolioOptimizerInputSchema},
  output: {schema: PortfolioOptimizerOutputSchema},
  prompt: `You are an expert design consultant specializing in portfolio optimization. Your goal is to provide actionable suggestions for improving a user's portfolio based on current design trends and the user's specific goals.

  Here's a description of the user's current portfolio:
  {{portfolioDescription}}

  The user's goals for their portfolio are:
  {{designGoals}}

  Based on this information, provide a ranked list of suggestions for improving the portfolio. Each suggestion should include a confidence score (0-1) indicating the likelihood that the suggestion will increase views or engagement, and reasoning behind the suggestion, including references to trending design styles and how it will help the user achieve their goals.

  Ensure that suggestions are detailed and practical. Return the suggestions in the requested JSON format.
  `,
});

const portfolioOptimizerFlow = ai.defineFlow(
  {
    name: 'portfolioOptimizerFlow',
    inputSchema: PortfolioOptimizerInputSchema,
    outputSchema: PortfolioOptimizerOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
